#!/bin/bash

NUM_EPOCHS=2
FEATURE_MUL=100
FEATURE_CON=-30
LABEL_MULTI=0.3
LEARNING_RATE=0.15
BETA_VALUE=0.1
NUM_NEURONS=100
CONNECTIONS_TYPE=a


python SL-training.py exp01-29-05-2025 $NUM_NEURONS y $NUM_EPOCHS $LEARNING_RATE r 0 $FEATURE_MUL $FEATURE_CON $LABEL_MULTI $BETA_VALUE $CONNECTIONS_TYPE